### ISSUE TITLE
Attempting to dye reinforced shulker box produces vanilla dyed shulker box 

### ISSUE THREAD

**Issue by RubyRezal** [Aton-Kish/reinforced-shulker-boxes#16]
Minecraft 1.18.1
Fabric 0.12.12
Reinforced Shulker Boxes 1.1.5

Trying to dye a reinforced shulker box does not produce expected output of a dyed reinforced shulker box.

Recipes for dyeing reinforced shulker boxes do not appear in REI.
![2021-12-28_14 21 32](https://user-images.githubusercontent.com/1816386/147600304-f0e8110d-accd-4cab-9d9a-6876f7b36d9f.png)
![2021-12-28_14 22 04](https://user-images.githubusercontent.com/1816386/147600309-4f2d0fd9-0d56-4f23-bd38-c99234d58b2d.png)

**Comment by Aton-Kish** [comment]
Thank you for reporting:)
It seems there have been recipe conflicts between the vanilla coloring and my mod coloring.
And I think the vanilla recipes were displayed preferentially in your play environment.

> Recipes for dyeing reinforced shulker boxes do not appear in REI.

This is the correct behavior as specified because I respect vanilla's behavior. (vanilla's dyeing recipes aren't also displayed.)

**Comment by Aton-Kish** [comment]
fixed in version 1.1.6
<https://www.curseforge.com/minecraft/mc-mods/reinforced-shulker-boxes>
